### ISSUE TITLE
News sidebar: There are seven published news items but only five are displayed in the section.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Lochness-Landscaping-Services#14]
![image](https://cloud.githubusercontent.com/assets/11186313/8298738/c7fc604a-199f-11e5-9bd6-e16604a13675.png)

**Comment by ramoncebudigital** [comment]
refer to this link: https://github.com/titan-cebu/Lochness-Landscaping-Services/issues/8
