### ISSUE TITLE
Services page: For list layouts, NEVER use the default “no-image” if item has no image.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Lochness-Landscaping-Services#33]
Please see standards:
https://knowledgebase.titanweb.com.au/implementation-practices/woocommerce/default-no-image

**Comment by roseliesromeo** [comment]
Apply fixes to News listing page.

**Comment by rexcebudigital** [comment]
Its already implemented.

**Comment by roseliesromeo** [comment]
Default no-image is still used for news items without featured images.
![image](https://cloud.githubusercontent.com/assets/11186313/8400182/d0009bba-1e4c-11e5-8093-7d65f4ec1b84.png)
