### ISSUE TITLE
Home - lead-ins: Font color for the Service title should be #8dc63f instead of #517b34

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Lochness-Landscaping-Services#40]
![image](https://cloud.githubusercontent.com/assets/11186313/8301334/943a8c9e-19bf-11e5-9b96-6c43eafefedc.png)

**Comment by ramoncebudigital** [comment]
Services titile would base on the Header tab hover color.
see screenshot:
![screenshot_1](https://cloud.githubusercontent.com/assets/11186436/8324860/ff0cbd90-1a86-11e5-84c2-7a913b12776e.png)

**Comment by roseliesromeo** [comment]
Let's do for the first service title then as specified in the design.
