### ISSUE TITLE
Home: Page should be using Projects ACF [ slick banner ] as per scope.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Lochness-Landscaping-Services#57]
Currently, there is no projects ACF in the home page.
![image](https://cloud.githubusercontent.com/assets/11186313/8400618/42b1aaf8-1e54-11e5-9786-51e0d2b85dcf.png)

**Comment by christiancebudigital** [comment]
Hi Roselie, 

I've updated the google spreadsheet, that was my error, I've already updated the projects acf to projects custom post type, which will display featured image.
