### ISSUE TITLE
Services - sidebar: Not all services custom posts are displayed in the sidebar section.

### ISSUE THREAD

**Issue by roseliesromeo** [titan-cebu/Lochness-Landscaping-Services#8]
![image](https://cloud.githubusercontent.com/assets/11186313/8298295/c2af8d52-1999-11e5-99de-cff0f0d2e671.png)

**Comment by ramoncebudigital** [comment]
Base on the design only 5 will be display and there's no documentation for this to display all serivces in the sidebar. The sidebar services is like "featured services".

**Comment by roseliesromeo** [comment]
This is the usual implementation if there is list of services in the sidebar section.  And besides, there is no way to rearrange or to choose which services are to be displayed in the section.
